<?php
$sender="root@localhost";
$adminRecip="steve.t.haber+serverside@gmail.com";
$voiceFrom="+12342342342";
$voiceTo="+12342342342";
$voiceUrl="http://somewhere/VillageCarService/callback.php";
$voiceAccountSid="Aasdfasdfsadfasdfsadfasdfsadfasdfasdfb3ece2";
$voiceAccountSecret="6basdfasdfasdfasdfasdfasdfasdfasdf2";
?>
